### ISSUE TITLE
需要新增 User-Agent 和 cf_clearance 才能正常使用

### ISSUE THREAD

**Issue by supgeek-rod** [onekb/ChatGPT#2]
使用 `onekb/chat-gpt: 1.0.3` 折腾了两三个小时，openai 一直返回 403
对比 https://github.com/acheong08/ChatGPT/blob/45659c12aeac12bbee48a9fa6c6b026371433ad0/config.json.example#L1-L5
发现少了 `User-Agent` 和 `cf_clearance`，加上之后就正常了

## 失败返回如下
```
$ php chatgpt.php
🐚 问问神奇海螺：dd
让我想想。
^ """
Client error: `POST https://chat.openai.com/backend-api/conversation` resulted in a `403 Forbidden` response:\n
<!DOCTYPE html>\n
<html lang="en-US">\n
<head>\n
    <title>Just a moment...</title>\n
    <meta http-equiv="Content-Type" conte (truncated...)\n
"""
^ "可能是因为网络原因，请求中断，你可以再问一次。"
```

## 成功返回如下
```
$ php chatgpt.php
🐚 问问神奇海螺：abc
让我想想。
^ array:3 [
  "answer" => "I'm sorry, but I'm not sure what you're asking. Could you please provide more information or context? I'm a large language model trained by OpenAI and I don't have access to the internet, so I can only provide information based on what I've been trained on"
  "conversationID" => "387e41d9-7afd-4b8d-b1a0-2de93736e655"
  "parentMessageId" => "7708dd76-d53c-46de-958a-e5c96c87a714"
]
```

**Comment by onekb** [comment]
上午的时候发现了，官网那加了cloudflare，也看到其他语言包issue里一片哀嚎。
本来要去改的，但是cf_clearance最多只能坚持两小时，感到心累，意味着每两小时要手工刷新一次。（我不认为防cc攻击的JS能轻松绕过去）
然后去看看能不能用官方的API，结果GPT用的模型text-davinci-002-render，但是没有开放出来，公开的API只有text-davinci-003，这个003给出来的回答实在是太弱智了。
完善这两个参数的推送我晚点更新出来吧，也要看看官方的态度，如果能提供API可能就不用那么忙活了。

**Comment by superodv3** [comment]
不知什么原因，明天调通的 `acheong08
/ChatGPT` 和本项目(添加了 User-Agent 和 cf_clearance)，今天就彻底不行了(chat.openai.com 访问正常)，期间更换了多次 config 参数，折腾了两个小时还是不行。

**Comment by onekb** [comment]
> 不知什么原因，明天调通的 `acheong08 /ChatGPT` 和本项目(添加了 User-Agent 和 cf_clearance)，今天就彻底不行了(chat.openai.com 访问正常)，期间更换了多次 config 参数，折腾了两个小时还是不行。

cf_clearance有效期只有两小时，而且要保证UA和IP一致，这东西是防cc的，可以抓包看看，尽可能保证脚本和浏览器的header参数和IP出口一致。

**Comment by onekb** [comment]
已更新 https://github.com/onekb/ChatGPT/releases/tag/1.0.5

**Comment by superodv3** [comment]
@onekb Grate Job 👍 

我是 UserAgent / cf_clearance / session / Authorized 都换了三五轮都不行，使用 ApiFox 来发 http 请求到 chat.openai.com 带了 cf_clearance 也返回的是 cf 的页面。

请教一下咱们这个包的原理是什么呢？使用 curl 以及 ApiFox 等工具是可以正常使用 chat.openai.com 吗？

**Comment by onekb** [comment]
> @onekb Grate Job 👍
> 
> 我是 UserAgent / cf_clearance / session / Authorized 都换了三五轮都不行，使用 ApiFox 来发 http 请求到 chat.openai.com 带了 cf_clearance 也返回的是 cf 的页面。
> 
> 请教一下咱们这个包的原理是什么呢？使用 curl 以及 ApiFox 等工具是可以正常使用 chat.openai.com 吗？

无论是curl还是apifox都是可以实现的，http是无状态访问，你提交什么服务器认什么。
可以使用一个小技巧：
1. 浏览器F12审查抓包的时候，右键选择复制curl。
2. 然后你用apifox构建一样的请求，右上角有个生成代码的按钮，选择curl。
3. 对比两边的参数有什么差异，以浏览器的curl为准。

这个包谈不上什么原理，无非就是模拟请求，其他语言的包也是一样实现的。
