### ISSUE TITLE
  cURL error 60: SSL certificate problem: unable to get local issuer certificat

### ISSUE THREAD

**Issue by crsec** [onekb/ChatGPT#5]
[GuzzleHttp\Exception\RequestException]
  cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://chat.openai.com/api/auth/session

**Comment by onekb** [comment]
非扩展包问题，详情参考 [cURL error 60: SSL certificate: unable to get local issuer certificate](https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate)

**Comment by crsec** [comment]
https://blog.csdn.net/qq_37868757/article/details/120839679 设置了证书路径可用了
