### ISSUE TITLE
这两个 大小写不一致 逼死强迫症。。。

### ISSUE THREAD

**Issue by jmglsi** [onekb/ChatGPT#6]
'answer' => $answer,
'conversationID' => $conversationID,
'parentMessageId' => $parentID,

应该全部 conversationID parentMessageID 或者 全部 conversationId parentMessageId

**Comment by onekb** [comment]
因为我是翻译这个项目的 https://github.com/idootop/chatgpt-bot/blob/main/src/chat-bot/chatgpt.ts 甚至大部分代码都是靠ChatGPT帮我翻译的。
强迫症好治啊，多看不自在的，很快就脱敏了。
